In [3]:
import pandas as pd
import numpy as np
df=pd.read_csv("Sale_study.csv")
df

,Order_ID,Order_Date,Customer_ID,City,Product,Category,Quantity,Price,Discount_%,Total_Amount,Payment_Method
0,ORD2000,2025-01-29,CUST1000,Delhi,Tablet,Accessories,3,15521,0,46563.00,Cash
1,ORD2001,2025-02-11,CUST1001,Hyderabad,Tablet,Accessories,3,8681,15,22136.55,Cash
2,ORD2002,2025-01-02,CUST1002,Mumbai,Mobile,Accessories,1,40764,0,40764.00,Debit Card
3,ORD2003,2025-02-04,CUST1003,Bangalore,Headphones,Electronics,4,59575,15,202555.00,Cash
4,ORD2004,2025-01-04,CUST1004,Chennai,Headphones,Electronics,4,22180,0,88720.00,Cash
5,ORD2005,2025-01-11,CUST1005,Bangalore,Tablet,Electronics,1,17200,10,15480.00,Cash
6,ORD2006,2025-01-09,CUST1006,Chennai,Mobile,Accessories,4,78787,15,267875.80,Credit Card
7,ORD2007,2025-02-27,CUST1007,Delhi,Headphones,Accessories,3,28191,0,84573.00,Cash
8,ORD2008,2025-01-06,CUST1008,Delhi,Smartwatch,Electronics,5,13275,15,56418.75,Cash
9,ORD2009,2025-01-05,CUST1009,Hyderabad,Laptop,Accessories,3,67787,0,203361.00,Debit Card
10,ORD2010,2025-02-25,CUST1010,Mumbai,Laptop,Electronics,1,44947,5,42699.65,Credit Card
11,ORD2011,2025-01-29,CUST1011,Mumbai,Mobile,Electronics,4,33833,15,115032.20,Cash
12,ORD2012,2025-02-13,CUST1012,Delhi,Laptop,Electronics,4,66676,15,226698.40,UPI
13,ORD2013,2025-01-11,CUST1013,Bangalore,Headphones,Electronics,4,2663,15,9054.20,UPI
14,ORD2014,2025-01-25,CUST1014,Delhi,Smartwatch,Accessories,3,11543,15,29434.65,Net Banking
15,ORD2015,2025-01-04,CUST1015,Hyderabad,Tablet,Electronics,2,65587,10,118056.60,UPI
16,ORD2016,2025-02-26,CUST1016,Hyderabad,Headphones,Electronics,3,34294,5,97737.90,Net Banking
17,ORD2017,2025-02-05,CUST1017,Hyderabad,Mobile,Accessories,3,78815,15,200978.25,UPI
18,ORD2018,2025-01-20,CUST1018,Mumbai,Smartwatch,Electronics,5,2003,15,8512.75,UPI
19,ORD2019,2025-01-27,CUST1019,Bangalore,Laptop,Electronics,5,50222,0,251110.00,Debit Card
20,ORD2020,2025-01-09,CUST1020,Bangalore,Laptop,Accessories,5,34282,0,171410.00,Credit Card
21,ORD2021,2025-02-25,CUST1021,Mumbai,Headphones,Electronics,1,59405,0,59405.00,Debit Card
22,ORD2022,2025-01-30,CUST1022,Mumbai,Mobile,Electronics,5,54028,0,270140.00,UPI
23,ORD2023,2025-01-02,CUST1023,Bangalore,Mobile,Accessories,3,69156,10,186721.20,Net Banking
24,ORD2024,2025-01-01,CUST1024,Hyderabad,Laptop,Electronics,1,12564,10,11307.60,Debit Card
25,ORD2025,2025-01-11,CUST1025,Bangalore,Smartwatch,Accessories,5,41352,10,186084.00,UPI
26,ORD2026,2025-02-08,CUST1026,Mumbai,Mobile,Accessories,3,36541,15,93179.55,Net Banking
27,ORD2027,2025-01-18,CUST1027,Delhi,Headphones,Electronics,2,18001,15,30601.70,Credit Card
28,ORD2028,2025-01-15,CUST1028,Delhi,Tablet,Electronics,4,68520,15,232968.00,Cash
29,ORD2029,2025-02-18,CUST1029,Bangalore,Laptop,Electronics,5,29924,0,149620.00,Credit Card
30,ORD2030,2025-02-10,CUST1030,Chennai,Mobile,Electronics,4,65186,0,260744.00,Debit Card
31,ORD2031,2025-02-27,CUST1031,Delhi,Laptop,Electronics,2,22370,10,40266.00,Net Banking
32,ORD2032,2025-02-07,CUST1032,Bangalore,Smartwatch,Electronics,5,18475,10,83137.50,Credit Card
33,ORD2033,2025-02-27,CUST1033,Hyderabad,Headphones,Electronics,3,33176,0,99528.00,Credit Card
34,ORD2034,2025-02-01,CUST1034,Bangalore,Laptop,Electronics,1,10987,5,10437.65,Cash
35,ORD2035,2025-02-22,CUST1035,Bangalore,Smartwatch,Electronics,2,22797,15,38754.90,Debit Card
36,ORD2036,2025-02-21,CUST1036,Delhi,Tablet,Electronics,1,65023,5,61771.85,Net Banking
37,ORD2037,2025-02-27,CUST1037,Chennai,Smartwatch,Electronics,4,70485,0,281940.00,Net Banking
38,ORD2038,2025-02-22,CUST1038,Bangalore,Headphones,Electronics,5,57021,10,256594.50,Credit Card
39,ORD2039,2025-02-01,CUST1039,Delhi,Tablet,Accessories,1,68505,5,65079.75,Cash
40,ORD2040,2025-02-28,CUST1040,Delhi,Laptop,Electronics,4,58190,0,232760.00,Credit Card
41,ORD2041,2025-02-28,CUST1041,Delhi,Smartwatch,Accessories,3,7462,0,22386.00,Net Banking
42,ORD2042,2025-01-01,CUST1042,Bangalore,Smartwatch,Accessories,4,1587,5,6030.60,Net Banking
43,ORD2043,2025-02-20,CUST1043,Bangalore,Mobile,Electronics,5,29916,15,127143.00,Cash
44,ORD2044,2025-02-15,CUST1044,Bangalore,Smartwatch,Electronics,2,78251,5,148676.90,Debit Card
45,ORD2045,2025-02-20,CUST1045,Bangalore,Mobile,Electronics,2,28059,5,53312.10,Credit Card
46,ORD2046,2025-01-24,CUST1046,Hyderabad,Headphones,Accessories,5,37095,5,176201.25,Cash
47,ORD2047,2025-01-07,CUST1047,Bangalore,Mobile,Electronics,2,35710,5,67849.00,Cash
48,ORD2048,2025-01-30,CUST1048,Mumbai,Laptop,Accessories,2,75151,5,142786.90,Credit Card
49,ORD2049,2025-02-03,CUST1049,Mumbai,Laptop,Electronics,3,11388,10,30747.60,Debit Card

In [5]:
#1.	Find total sales (Total_Amount).
Total_Sales=df["Total_Amount"].sum()
print("Total Sales:",Total_Sales)

Total Sales: 5725346.25

In [6]:
# 2.	Calculate average order value.
Avg_VAlue=df["Total_Amount"].mean()
print("Average Value:",Avg_VAlue)

Average Value: 114506.925

In [8]:
# 3.	Count total orders per city.
Total_Order_PerCity=df["City"].value_counts()
print("Count total orders per city:",Total_Order_PerCity)

Count total orders per city: City
Bangalore    17
Delhi        12
Mumbai        9
Hyderabad     8
Chennai       4
Name: count, dtype: int64

In [11]:
# 4.Find highest and lowest order amount.
Highest_Amount=df["Total_Amount"].max()
Lowest_Amount=df["Total_Amount"].min()
print("Highest_Amount:",Highest_Amount)
print("Lowest_Amount:",Lowest_Amount)

Highest_Amount: 281940.0
Lowest_Amount: 6030.6

In [12]:
# 5.Which product is sold most (based on quantity)?
product=df.groupby("Product")["Quantity"].sum().idxmax()
print("Most Sold Product:",product)

Most Sold Product: Smartwatch

In [13]:
# 6.Calculate total sales by City.
sales_by_city=df.groupby("City")["Total_Amount"].sum()
sales_by_city

City
Bangalore    1963970.55
Chennai       899279.80
Delhi        1129521.10
Hyderabad     929307.15
Mumbai        803267.65
Name: Total_Amount, dtype: float64

In [14]:
# 7.Calculate total sales by Product.
sales_prod = df.groupby("Product")["Total_Amount"].sum()
print(sales_prod)

Product
Headphones    1104970.55
Laptop        1513204.80
Mobile        1683739.10
Smartwatch     861376.05
Tablet         562055.75
Name: Total_Amount, dtype: float64

In [16]:
# 8.Find average discount by Category.
Category=df.groupby("Category")["Discount_%"].mean()
Category

Category
Accessories    6.764706
Electronics    7.727273
Name: Discount_%, dtype: float64

In [17]:
# 9.Find total revenue by Payment_Method.
r=df.groupby("Payment_Method")['Total_Amount'].sum() 
r

Payment_Method
Cash           1311157.15
Credit Card    1530326.15
Debit Card     1044871.00
Net Banking     819467.75
UPI            1019524.20
Name: Total_Amount, dtype: float64

In [19]:
# 10.	Which city generated the highest revenue?
highest_revenue=df.groupby('City')['Total_Amount'].sum().idxmax()
highest_revenue

'Bangalore'

In [22]:
# 11.	Show orders where Discount_% > 10.
dis = df[df["Discount_%"] > 10]
dis

,Order_ID,Order_Date,Customer_ID,City,Product,Category,Quantity,Price,Discount_%,Total_Amount,Payment_Method
1,ORD2001,2025-02-11,CUST1001,Hyderabad,Tablet,Accessories,3,8681,15,22136.55,Cash
3,ORD2003,2025-02-04,CUST1003,Bangalore,Headphones,Electronics,4,59575,15,202555.00,Cash
6,ORD2006,2025-01-09,CUST1006,Chennai,Mobile,Accessories,4,78787,15,267875.80,Credit Card
8,ORD2008,2025-01-06,CUST1008,Delhi,Smartwatch,Electronics,5,13275,15,56418.75,Cash
11,ORD2011,2025-01-29,CUST1011,Mumbai,Mobile,Electronics,4,33833,15,115032.20,Cash
12,ORD2012,2025-02-13,CUST1012,Delhi,Laptop,Electronics,4,66676,15,226698.40,UPI
13,ORD2013,2025-01-11,CUST1013,Bangalore,Headphones,Electronics,4,2663,15,9054.20,UPI
14,ORD2014,2025-01-25,CUST1014,Delhi,Smartwatch,Accessories,3,11543,15,29434.65,Net Banking
17,ORD2017,2025-02-05,CUST1017,Hyderabad,Mobile,Accessories,3,78815,15,200978.25,UPI
18,ORD2018,2025-01-20,CUST1018,Mumbai,Smartwatch,Electronics,5,2003,15,8512.75,UPI
26,ORD2026,2025-02-08,CUST1026,Mumbai,Mobile,Accessories,3,36541,15,93179.55,Net Banking
27,ORD2027,2025-01-18,CUST1027,Delhi,Headphones,Electronics,2,18001,15,30601.70,Credit Card
28,ORD2028,2025-01-15,CUST1028,Delhi,Tablet,Electronics,4,68520,15,232968.00,Cash
35,ORD2035,2025-02-22,CUST1035,Bangalore,Smartwatch,Electronics,2,22797,15,38754.90,Debit Card
43,ORD2043,2025-02-20,CUST1043,Bangalore,Mobile,Electronics,5,29916,15,127143.00,Cash

In [25]:
orders_mumbai = df[df["City"] == "Mumbai"]
orders_mumbai

,Order_ID,Order_Date,Customer_ID,City,Product,Category,Quantity,Price,Discount_%,Total_Amount,Payment_Method
2,ORD2002,2025-01-02,CUST1002,Mumbai,Mobile,Accessories,1,40764,0,40764.00,Debit Card
10,ORD2010,2025-02-25,CUST1010,Mumbai,Laptop,Electronics,1,44947,5,42699.65,Credit Card
11,ORD2011,2025-01-29,CUST1011,Mumbai,Mobile,Electronics,4,33833,15,115032.20,Cash
18,ORD2018,2025-01-20,CUST1018,Mumbai,Smartwatch,Electronics,5,2003,15,8512.75,UPI
21,ORD2021,2025-02-25,CUST1021,Mumbai,Headphones,Electronics,1,59405,0,59405.00,Debit Card
22,ORD2022,2025-01-30,CUST1022,Mumbai,Mobile,Electronics,5,54028,0,270140.00,UPI
26,ORD2026,2025-02-08,CUST1026,Mumbai,Mobile,Accessories,3,36541,15,93179.55,Net Banking
48,ORD2048,2025-01-30,CUST1048,Mumbai,Laptop,Accessories,2,75151,5,142786.90,Credit Card
49,ORD2049,2025-02-03,CUST1049,Mumbai,Laptop,Electronics,3,11388,10,30747.60,Debit Card

In [24]:
# 12.Find all orders from Mumbai.
Orders_Mumbai=df.loc[df['City']=='Mumbai']
print(Orders_Mumbai)

   Order_ID  Order_Date Customer_ID    City     Product     Category  \
2   ORD2002  2025-01-02    CUST1002  Mumbai      Mobile  Accessories
10  ORD2010  2025-02-25    CUST1010  Mumbai      Laptop  Electronics
11  ORD2011  2025-01-29    CUST1011  Mumbai      Mobile  Electronics
18  ORD2018  2025-01-20    CUST1018  Mumbai  Smartwatch  Electronics
21  ORD2021  2025-02-25    CUST1021  Mumbai  Headphones  Electronics
22  ORD2022  2025-01-30    CUST1022  Mumbai      Mobile  Electronics
26  ORD2026  2025-02-08    CUST1026  Mumbai      Mobile  Accessories
48  ORD2048  2025-01-30    CUST1048  Mumbai      Laptop  Accessories
49  ORD2049  2025-02-03    CUST1049  Mumbai      Laptop  Electronics

    Quantity  Price  Discount_%  Total_Amount Payment_Method
2          1  40764           0      40764.00     Debit Card
10         1  44947           5      42699.65    Credit Card
11         4  33833          15     115032.20           Cash
18         5   2003          15       8512.75            UPI
21         1  59405           0      59405.00     Debit Card
22         5  54028           0     270140.00            UPI
26         3  36541          15      93179.55    Net Banking
48         2  75151           5     142786.90    Credit Card
49         3  11388          10      30747.60     Debit Card

In [26]:
# 13.	Show orders where Quantity ≥ 3.
df[df['Quantity'] >= 3]

,Order_ID,Order_Date,Customer_ID,City,Product,Category,Quantity,Price,Discount_%,Total_Amount,Payment_Method
0,ORD2000,2025-01-29,CUST1000,Delhi,Tablet,Accessories,3,15521,0,46563.00,Cash
1,ORD2001,2025-02-11,CUST1001,Hyderabad,Tablet,Accessories,3,8681,15,22136.55,Cash
3,ORD2003,2025-02-04,CUST1003,Bangalore,Headphones,Electronics,4,59575,15,202555.00,Cash
4,ORD2004,2025-01-04,CUST1004,Chennai,Headphones,Electronics,4,22180,0,88720.00,Cash
6,ORD2006,2025-01-09,CUST1006,Chennai,Mobile,Accessories,4,78787,15,267875.80,Credit Card
7,ORD2007,2025-02-27,CUST1007,Delhi,Headphones,Accessories,3,28191,0,84573.00,Cash
8,ORD2008,2025-01-06,CUST1008,Delhi,Smartwatch,Electronics,5,13275,15,56418.75,Cash
9,ORD2009,2025-01-05,CUST1009,Hyderabad,Laptop,Accessories,3,67787,0,203361.00,Debit Card
11,ORD2011,2025-01-29,CUST1011,Mumbai,Mobile,Electronics,4,33833,15,115032.20,Cash
12,ORD2012,2025-02-13,CUST1012,Delhi,Laptop,Electronics,4,66676,15,226698.40,UPI
13,ORD2013,2025-01-11,CUST1013,Bangalore,Headphones,Electronics,4,2663,15,9054.20,UPI
14,ORD2014,2025-01-25,CUST1014,Delhi,Smartwatch,Accessories,3,11543,15,29434.65,Net Banking
16,ORD2016,2025-02-26,CUST1016,Hyderabad,Headphones,Electronics,3,34294,5,97737.90,Net Banking
17,ORD2017,2025-02-05,CUST1017,Hyderabad,Mobile,Accessories,3,78815,15,200978.25,UPI
18,ORD2018,2025-01-20,CUST1018,Mumbai,Smartwatch,Electronics,5,2003,15,8512.75,UPI
19,ORD2019,2025-01-27,CUST1019,Bangalore,Laptop,Electronics,5,50222,0,251110.00,Debit Card
20,ORD2020,2025-01-09,CUST1020,Bangalore,Laptop,Accessories,5,34282,0,171410.00,Credit Card
22,ORD2022,2025-01-30,CUST1022,Mumbai,Mobile,Electronics,5,54028,0,270140.00,UPI
23,ORD2023,2025-01-02,CUST1023,Bangalore,Mobile,Accessories,3,69156,10,186721.20,Net Banking
25,ORD2025,2025-01-11,CUST1025,Bangalore,Smartwatch,Accessories,5,41352,10,186084.00,UPI
26,ORD2026,2025-02-08,CUST1026,Mumbai,Mobile,Accessories,3,36541,15,93179.55,Net Banking
28,ORD2028,2025-01-15,CUST1028,Delhi,Tablet,Electronics,4,68520,15,232968.00,Cash
29,ORD2029,2025-02-18,CUST1029,Bangalore,Laptop,Electronics,5,29924,0,149620.00,Credit Card
30,ORD2030,2025-02-10,CUST1030,Chennai,Mobile,Electronics,4,65186,0,260744.00,Debit Card
32,ORD2032,2025-02-07,CUST1032,Bangalore,Smartwatch,Electronics,5,18475,10,83137.50,Credit Card
33,ORD2033,2025-02-27,CUST1033,Hyderabad,Headphones,Electronics,3,33176,0,99528.00,Credit Card
37,ORD2037,2025-02-27,CUST1037,Chennai,Smartwatch,Electronics,4,70485,0,281940.00,Net Banking
38,ORD2038,2025-02-22,CUST1038,Bangalore,Headphones,Electronics,5,57021,10,256594.50,Credit Card
40,ORD2040,2025-02-28,CUST1040,Delhi,Laptop,Electronics,4,58190,0,232760.00,Credit Card
41,ORD2041,2025-02-28,CUST1041,Delhi,Smartwatch,Accessories,3,7462,0,22386.00,Net Banking
42,ORD2042,2025-01-01,CUST1042,Bangalore,Smartwatch,Accessories,4,1587,5,6030.60,Net Banking
43,ORD2043,2025-02-20,CUST1043,Bangalore,Mobile,Electronics,5,29916,15,127143.00,Cash
46,ORD2046,2025-01-24,CUST1046,Hyderabad,Headphones,Accessories,5,37095,5,176201.25,Cash
49,ORD2049,2025-02-03,CUST1049,Mumbai,Laptop,Electronics,3,11388,10,30747.60,Debit Card

In [27]:
# 14.Find orders paid using UPI.
upi=df[df['Payment_Method']=='UPI']
print(upi)

   Order_ID  Order_Date Customer_ID       City     Product     Category  \
12  ORD2012  2025-02-13    CUST1012      Delhi      Laptop  Electronics
13  ORD2013  2025-01-11    CUST1013  Bangalore  Headphones  Electronics
15  ORD2015  2025-01-04    CUST1015  Hyderabad      Tablet  Electronics
17  ORD2017  2025-02-05    CUST1017  Hyderabad      Mobile  Accessories
18  ORD2018  2025-01-20    CUST1018     Mumbai  Smartwatch  Electronics
22  ORD2022  2025-01-30    CUST1022     Mumbai      Mobile  Electronics
25  ORD2025  2025-01-11    CUST1025  Bangalore  Smartwatch  Accessories

    Quantity  Price  Discount_%  Total_Amount Payment_Method
12         4  66676          15     226698.40            UPI
13         4   2663          15       9054.20            UPI
15         2  65587          10     118056.60            UPI
17         3  78815          15     200978.25            UPI
18         5   2003          15       8512.75            UPI
22         5  54028           0     270140.00            UPI
25         5  41352          10     186084.00            UPI

In [29]:
# 15.Find Electronics category sales only.
electronics_sales = df[df['Category'] == 'Electronics']
(electronics_sales)

,Order_ID,Order_Date,Customer_ID,City,Product,Category,Quantity,Price,Discount_%,Total_Amount,Payment_Method
3,ORD2003,2025-02-04,CUST1003,Bangalore,Headphones,Electronics,4,59575,15,202555.00,Cash
4,ORD2004,2025-01-04,CUST1004,Chennai,Headphones,Electronics,4,22180,0,88720.00,Cash
5,ORD2005,2025-01-11,CUST1005,Bangalore,Tablet,Electronics,1,17200,10,15480.00,Cash
8,ORD2008,2025-01-06,CUST1008,Delhi,Smartwatch,Electronics,5,13275,15,56418.75,Cash
10,ORD2010,2025-02-25,CUST1010,Mumbai,Laptop,Electronics,1,44947,5,42699.65,Credit Card
11,ORD2011,2025-01-29,CUST1011,Mumbai,Mobile,Electronics,4,33833,15,115032.20,Cash
12,ORD2012,2025-02-13,CUST1012,Delhi,Laptop,Electronics,4,66676,15,226698.40,UPI
13,ORD2013,2025-01-11,CUST1013,Bangalore,Headphones,Electronics,4,2663,15,9054.20,UPI
15,ORD2015,2025-01-04,CUST1015,Hyderabad,Tablet,Electronics,2,65587,10,118056.60,UPI
16,ORD2016,2025-02-26,CUST1016,Hyderabad,Headphones,Electronics,3,34294,5,97737.90,Net Banking
18,ORD2018,2025-01-20,CUST1018,Mumbai,Smartwatch,Electronics,5,2003,15,8512.75,UPI
19,ORD2019,2025-01-27,CUST1019,Bangalore,Laptop,Electronics,5,50222,0,251110.00,Debit Card
21,ORD2021,2025-02-25,CUST1021,Mumbai,Headphones,Electronics,1,59405,0,59405.00,Debit Card
22,ORD2022,2025-01-30,CUST1022,Mumbai,Mobile,Electronics,5,54028,0,270140.00,UPI
24,ORD2024,2025-01-01,CUST1024,Hyderabad,Laptop,Electronics,1,12564,10,11307.60,Debit Card
27,ORD2027,2025-01-18,CUST1027,Delhi,Headphones,Electronics,2,18001,15,30601.70,Credit Card
28,ORD2028,2025-01-15,CUST1028,Delhi,Tablet,Electronics,4,68520,15,232968.00,Cash
29,ORD2029,2025-02-18,CUST1029,Bangalore,Laptop,Electronics,5,29924,0,149620.00,Credit Card
30,ORD2030,2025-02-10,CUST1030,Chennai,Mobile,Electronics,4,65186,0,260744.00,Debit Card
31,ORD2031,2025-02-27,CUST1031,Delhi,Laptop,Electronics,2,22370,10,40266.00,Net Banking
32,ORD2032,2025-02-07,CUST1032,Bangalore,Smartwatch,Electronics,5,18475,10,83137.50,Credit Card
33,ORD2033,2025-02-27,CUST1033,Hyderabad,Headphones,Electronics,3,33176,0,99528.00,Credit Card
34,ORD2034,2025-02-01,CUST1034,Bangalore,Laptop,Electronics,1,10987,5,10437.65,Cash
35,ORD2035,2025-02-22,CUST1035,Bangalore,Smartwatch,Electronics,2,22797,15,38754.90,Debit Card
36,ORD2036,2025-02-21,CUST1036,Delhi,Tablet,Electronics,1,65023,5,61771.85,Net Banking
37,ORD2037,2025-02-27,CUST1037,Chennai,Smartwatch,Electronics,4,70485,0,281940.00,Net Banking
38,ORD2038,2025-02-22,CUST1038,Bangalore,Headphones,Electronics,5,57021,10,256594.50,Credit Card
40,ORD2040,2025-02-28,CUST1040,Delhi,Laptop,Electronics,4,58190,0,232760.00,Credit Card
43,ORD2043,2025-02-20,CUST1043,Bangalore,Mobile,Electronics,5,29916,15,127143.00,Cash
44,ORD2044,2025-02-15,CUST1044,Bangalore,Smartwatch,Electronics,2,78251,5,148676.90,Debit Card
45,ORD2045,2025-02-20,CUST1045,Bangalore,Mobile,Electronics,2,28059,5,53312.10,Credit Card
47,ORD2047,2025-01-07,CUST1047,Bangalore,Mobile,Electronics,2,35710,5,67849.00,Cash
49,ORD2049,2025-02-03,CUST1049,Mumbai,Laptop,Electronics,3,11388,10,30747.60,Debit Card

In [30]:
# 16.Identify top 5 highest revenue orders.
high_order = df.sort_values(by=['Total_Amount'], ascending=False).head()
print(high_order)

   Order_ID  Order_Date Customer_ID       City     Product     Category  \
37  ORD2037  2025-02-27    CUST1037    Chennai  Smartwatch  Electronics
22  ORD2022  2025-01-30    CUST1022     Mumbai      Mobile  Electronics
6   ORD2006  2025-01-09    CUST1006    Chennai      Mobile  Accessories
30  ORD2030  2025-02-10    CUST1030    Chennai      Mobile  Electronics
38  ORD2038  2025-02-22    CUST1038  Bangalore  Headphones  Electronics

    Quantity  Price  Discount_%  Total_Amount Payment_Method
37         4  70485           0      281940.0    Net Banking
22         5  54028           0      270140.0            UPI
6          4  78787          15      267875.8    Credit Card
30         4  65186           0      260744.0     Debit Card
38         5  57021          10      256594.5    Credit Card

In [35]:
# 17.Find monthly sales trend.
df["Order_Date"]=pd.to_datetime(df["Order_Date"])
monthly_sales=df.groupby(df["Order_Date"].dt.month)["Total_Amount"].sum()
print(monthly_sales)

Order_Date
1    2732483.20
2    2992863.05
Name: Total_Amount, dtype: float64

In [36]:
# 18.Calculate total revenue after discount.
print("Calculate total revenue after discount",df["Total_Amount"].sum())

Calculate total revenue after discount 5725346.25

In [37]:
# 19.Which payment method is most used?
most_pay = df.groupby('Payment_Method')["Total_Amount"].sum().idxmax()
print(most_pay)

Credit Card

In [40]:
# 20.	Find repeat customers (if any).
df["Customer_ID"].value_counts()>1

Customer_ID
CUST1000    False
CUST1001    False
CUST1002    False
CUST1003    False
CUST1004    False
CUST1005    False
CUST1006    False
CUST1007    False
CUST1008    False
CUST1009    False
CUST1010    False
CUST1011    False
CUST1012    False
CUST1013    False
CUST1014    False
CUST1015    False
CUST1016    False
CUST1017    False
CUST1018    False
CUST1019    False
CUST1020    False
CUST1021    False
CUST1022    False
CUST1023    False
CUST1024    False
CUST1025    False
CUST1026    False
CUST1027    False
CUST1028    False
CUST1029    False
CUST1030    False
CUST1031    False
CUST1032    False
CUST1033    False
CUST1034    False
CUST1035    False
CUST1036    False
CUST1037    False
CUST1038    False
CUST1039    False
CUST1040    False
CUST1041    False
CUST1042    False
CUST1043    False
CUST1044    False
CUST1045    False
CUST1046    False
CUST1047    False
CUST1048    False
CUST1049    False
Name: count, dtype: bool

In [41]:
#21.Create Profit Column(20%)
df["20%_Profit"]=df["Total_Amount"]*0.20
df

,Order_ID,Order_Date,Customer_ID,City,Product,Category,Quantity,Price,Discount_%,Total_Amount,Payment_Method,20%_Profit
0,ORD2000,2025-01-29,CUST1000,Delhi,Tablet,Accessories,3,15521,0,46563.00,Cash,9312.60
1,ORD2001,2025-02-11,CUST1001,Hyderabad,Tablet,Accessories,3,8681,15,22136.55,Cash,4427.31
2,ORD2002,2025-01-02,CUST1002,Mumbai,Mobile,Accessories,1,40764,0,40764.00,Debit Card,8152.80
3,ORD2003,2025-02-04,CUST1003,Bangalore,Headphones,Electronics,4,59575,15,202555.00,Cash,40511.00
4,ORD2004,2025-01-04,CUST1004,Chennai,Headphones,Electronics,4,22180,0,88720.00,Cash,17744.00
5,ORD2005,2025-01-11,CUST1005,Bangalore,Tablet,Electronics,1,17200,10,15480.00,Cash,3096.00
6,ORD2006,2025-01-09,CUST1006,Chennai,Mobile,Accessories,4,78787,15,267875.80,Credit Card,53575.16
7,ORD2007,2025-02-27,CUST1007,Delhi,Headphones,Accessories,3,28191,0,84573.00,Cash,16914.60
8,ORD2008,2025-01-06,CUST1008,Delhi,Smartwatch,Electronics,5,13275,15,56418.75,Cash,11283.75
9,ORD2009,2025-01-05,CUST1009,Hyderabad,Laptop,Accessories,3,67787,0,203361.00,Debit Card,40672.20
10,ORD2010,2025-02-25,CUST1010,Mumbai,Laptop,Electronics,1,44947,5,42699.65,Credit Card,8539.93
11,ORD2011,2025-01-29,CUST1011,Mumbai,Mobile,Electronics,4,33833,15,115032.20,Cash,23006.44
12,ORD2012,2025-02-13,CUST1012,Delhi,Laptop,Electronics,4,66676,15,226698.40,UPI,45339.68
13,ORD2013,2025-01-11,CUST1013,Bangalore,Headphones,Electronics,4,2663,15,9054.20,UPI,1810.84
14,ORD2014,2025-01-25,CUST1014,Delhi,Smartwatch,Accessories,3,11543,15,29434.65,Net Banking,5886.93
15,ORD2015,2025-01-04,CUST1015,Hyderabad,Tablet,Electronics,2,65587,10,118056.60,UPI,23611.32
16,ORD2016,2025-02-26,CUST1016,Hyderabad,Headphones,Electronics,3,34294,5,97737.90,Net Banking,19547.58
17,ORD2017,2025-02-05,CUST1017,Hyderabad,Mobile,Accessories,3,78815,15,200978.25,UPI,40195.65
18,ORD2018,2025-01-20,CUST1018,Mumbai,Smartwatch,Electronics,5,2003,15,8512.75,UPI,1702.55
19,ORD2019,2025-01-27,CUST1019,Bangalore,Laptop,Electronics,5,50222,0,251110.00,Debit Card,50222.00
20,ORD2020,2025-01-09,CUST1020,Bangalore,Laptop,Accessories,5,34282,0,171410.00,Credit Card,34282.00
21,ORD2021,2025-02-25,CUST1021,Mumbai,Headphones,Electronics,1,59405,0,59405.00,Debit Card,11881.00
22,ORD2022,2025-01-30,CUST1022,Mumbai,Mobile,Electronics,5,54028,0,270140.00,UPI,54028.00
23,ORD2023,2025-01-02,CUST1023,Bangalore,Mobile,Accessories,3,69156,10,186721.20,Net Banking,37344.24
24,ORD2024,2025-01-01,CUST1024,Hyderabad,Laptop,Electronics,1,12564,10,11307.60,Debit Card,2261.52
25,ORD2025,2025-01-11,CUST1025,Bangalore,Smartwatch,Accessories,5,41352,10,186084.00,UPI,37216.80
26,ORD2026,2025-02-08,CUST1026,Mumbai,Mobile,Accessories,3,36541,15,93179.55,Net Banking,18635.91
27,ORD2027,2025-01-18,CUST1027,Delhi,Headphones,Electronics,2,18001,15,30601.70,Credit Card,6120.34
28,ORD2028,2025-01-15,CUST1028,Delhi,Tablet,Electronics,4,68520,15,232968.00,Cash,46593.60
29,ORD2029,2025-02-18,CUST1029,Bangalore,Laptop,Electronics,5,29924,0,149620.00,Credit Card,29924.00
30,ORD2030,2025-02-10,CUST1030,Chennai,Mobile,Electronics,4,65186,0,260744.00,Debit Card,52148.80
31,ORD2031,2025-02-27,CUST1031,Delhi,Laptop,Electronics,2,22370,10,40266.00,Net Banking,8053.20
32,ORD2032,2025-02-07,CUST1032,Bangalore,Smartwatch,Electronics,5,18475,10,83137.50,Credit Card,16627.50
33,ORD2033,2025-02-27,CUST1033,Hyderabad,Headphones,Electronics,3,33176,0,99528.00,Credit Card,19905.60
34,ORD2034,2025-02-01,CUST1034,Bangalore,Laptop,Electronics,1,10987,5,10437.65,Cash,2087.53
35,ORD2035,2025-02-22,CUST1035,Bangalore,Smartwatch,Electronics,2,22797,15,38754.90,Debit Card,7750.98
36,ORD2036,2025-02-21,CUST1036,Delhi,Tablet,Electronics,1,65023,5,61771.85,Net Banking,12354.37
37,ORD2037,2025-02-27,CUST1037,Chennai,Smartwatch,Electronics,4,70485,0,281940.00,Net Banking,56388.00
38,ORD2038,2025-02-22,CUST1038,Bangalore,Headphones,Electronics,5,57021,10,256594.50,Credit Card,51318.90
39,ORD2039,2025-02-01,CUST1039,Delhi,Tablet,Accessories,1,68505,5,65079.75,Cash,13015.95
40,ORD2040,2025-02-28,CUST1040,Delhi,Laptop,Electronics,4,58190,0,232760.00,Credit Card,46552.00
41,ORD2041,2025-02-28,CUST1041,Delhi,Smartwatch,Accessories,3,7462,0,22386.00,Net Banking,4477.20
42,ORD2042,2025-01-01,CUST1042,Bangalore,Smartwatch,Accessories,4,1587,5,6030.60,Net Banking,1206.12
43,ORD2043,2025-02-20,CUST1043,Bangalore,Mobile,Electronics,5,29916,15,127143.00,Cash,25428.60
44,ORD2044,2025-02-15,CUST1044,Bangalore,Smartwatch,Electronics,2,78251,5,148676.90,Debit Card,29735.38
45,ORD2045,2025-02-20,CUST1045,Bangalore,Mobile,Electronics,2,28059,5,53312.10,Credit Card,10662.42
46,ORD2046,2025-01-24,CUST1046,Hyderabad,Headphones,Accessories,5,37095,5,176201.25,Cash,35240.25
47,ORD2047,2025-01-07,CUST1047,Bangalore,Mobile,Electronics,2,35710,5,67849.00,Cash,13569.80
48,ORD2048,2025-01-30,CUST1048,Mumbai,Laptop,Accessories,2,75151,5,142786.90,Credit Card,28557.38
49,ORD2049,2025-02-03,CUST1049,Mumbai,Laptop,Electronics,3,11388,10,30747.60,Debit Card,6149.52

In [42]:
#22.Calculate and display City wise Average Value
Avg = df.groupby('City')["Total_Amount"].mean()
print(Avg)

City
Bangalore    115527.679412
Chennai      224819.950000
Delhi         94126.758333
Hyderabad    116163.393750
Mumbai        89251.961111
Name: Total_Amount, dtype: float64

In [43]:
#23.Sort Data In Descending Order By Total_Amount
df.sort_values(by=['Total_Amount'], ascending=False)

,Order_ID,Order_Date,Customer_ID,City,Product,Category,Quantity,Price,Discount_%,Total_Amount,Payment_Method,20%_Profit
37,ORD2037,2025-02-27,CUST1037,Chennai,Smartwatch,Electronics,4,70485,0,281940.00,Net Banking,56388.00
22,ORD2022,2025-01-30,CUST1022,Mumbai,Mobile,Electronics,5,54028,0,270140.00,UPI,54028.00
6,ORD2006,2025-01-09,CUST1006,Chennai,Mobile,Accessories,4,78787,15,267875.80,Credit Card,53575.16
30,ORD2030,2025-02-10,CUST1030,Chennai,Mobile,Electronics,4,65186,0,260744.00,Debit Card,52148.80
38,ORD2038,2025-02-22,CUST1038,Bangalore,Headphones,Electronics,5,57021,10,256594.50,Credit Card,51318.90
19,ORD2019,2025-01-27,CUST1019,Bangalore,Laptop,Electronics,5,50222,0,251110.00,Debit Card,50222.00
28,ORD2028,2025-01-15,CUST1028,Delhi,Tablet,Electronics,4,68520,15,232968.00,Cash,46593.60
40,ORD2040,2025-02-28,CUST1040,Delhi,Laptop,Electronics,4,58190,0,232760.00,Credit Card,46552.00
12,ORD2012,2025-02-13,CUST1012,Delhi,Laptop,Electronics,4,66676,15,226698.40,UPI,45339.68
9,ORD2009,2025-01-05,CUST1009,Hyderabad,Laptop,Accessories,3,67787,0,203361.00,Debit Card,40672.20
3,ORD2003,2025-02-04,CUST1003,Bangalore,Headphones,Electronics,4,59575,15,202555.00,Cash,40511.00
17,ORD2017,2025-02-05,CUST1017,Hyderabad,Mobile,Accessories,3,78815,15,200978.25,UPI,40195.65
23,ORD2023,2025-01-02,CUST1023,Bangalore,Mobile,Accessories,3,69156,10,186721.20,Net Banking,37344.24
25,ORD2025,2025-01-11,CUST1025,Bangalore,Smartwatch,Accessories,5,41352,10,186084.00,UPI,37216.80
46,ORD2046,2025-01-24,CUST1046,Hyderabad,Headphones,Accessories,5,37095,5,176201.25,Cash,35240.25
20,ORD2020,2025-01-09,CUST1020,Bangalore,Laptop,Accessories,5,34282,0,171410.00,Credit Card,34282.00
29,ORD2029,2025-02-18,CUST1029,Bangalore,Laptop,Electronics,5,29924,0,149620.00,Credit Card,29924.00
44,ORD2044,2025-02-15,CUST1044,Bangalore,Smartwatch,Electronics,2,78251,5,148676.90,Debit Card,29735.38
48,ORD2048,2025-01-30,CUST1048,Mumbai,Laptop,Accessories,2,75151,5,142786.90,Credit Card,28557.38
43,ORD2043,2025-02-20,CUST1043,Bangalore,Mobile,Electronics,5,29916,15,127143.00,Cash,25428.60
15,ORD2015,2025-01-04,CUST1015,Hyderabad,Tablet,Electronics,2,65587,10,118056.60,UPI,23611.32
11,ORD2011,2025-01-29,CUST1011,Mumbai,Mobile,Electronics,4,33833,15,115032.20,Cash,23006.44
33,ORD2033,2025-02-27,CUST1033,Hyderabad,Headphones,Electronics,3,33176,0,99528.00,Credit Card,19905.60
16,ORD2016,2025-02-26,CUST1016,Hyderabad,Headphones,Electronics,3,34294,5,97737.90,Net Banking,19547.58
26,ORD2026,2025-02-08,CUST1026,Mumbai,Mobile,Accessories,3,36541,15,93179.55,Net Banking,18635.91
4,ORD2004,2025-01-04,CUST1004,Chennai,Headphones,Electronics,4,22180,0,88720.00,Cash,17744.00
7,ORD2007,2025-02-27,CUST1007,Delhi,Headphones,Accessories,3,28191,0,84573.00,Cash,16914.60
32,ORD2032,2025-02-07,CUST1032,Bangalore,Smartwatch,Electronics,5,18475,10,83137.50,Credit Card,16627.50
47,ORD2047,2025-01-07,CUST1047,Bangalore,Mobile,Electronics,2,35710,5,67849.00,Cash,13569.80
39,ORD2039,2025-02-01,CUST1039,Delhi,Tablet,Accessories,1,68505,5,65079.75,Cash,13015.95
36,ORD2036,2025-02-21,CUST1036,Delhi,Tablet,Electronics,1,65023,5,61771.85,Net Banking,12354.37
21,ORD2021,2025-02-25,CUST1021,Mumbai,Headphones,Electronics,1,59405,0,59405.00,Debit Card,11881.00
8,ORD2008,2025-01-06,CUST1008,Delhi,Smartwatch,Electronics,5,13275,15,56418.75,Cash,11283.75
45,ORD2045,2025-02-20,CUST1045,Bangalore,Mobile,Electronics,2,28059,5,53312.10,Credit Card,10662.42
0,ORD2000,2025-01-29,CUST1000,Delhi,Tablet,Accessories,3,15521,0,46563.00,Cash,9312.60
10,ORD2010,2025-02-25,CUST1010,Mumbai,Laptop,Electronics,1,44947,5,42699.65,Credit Card,8539.93
2,ORD2002,2025-01-02,CUST1002,Mumbai,Mobile,Accessories,1,40764,0,40764.00,Debit Card,8152.80
31,ORD2031,2025-02-27,CUST1031,Delhi,Laptop,Electronics,2,22370,10,40266.00,Net Banking,8053.20
35,ORD2035,2025-02-22,CUST1035,Bangalore,Smartwatch,Electronics,2,22797,15,38754.90,Debit Card,7750.98
49,ORD2049,2025-02-03,CUST1049,Mumbai,Laptop,Electronics,3,11388,10,30747.60,Debit Card,6149.52
27,ORD2027,2025-01-18,CUST1027,Delhi,Headphones,Electronics,2,18001,15,30601.70,Credit Card,6120.34
14,ORD2014,2025-01-25,CUST1014,Delhi,Smartwatch,Accessories,3,11543,15,29434.65,Net Banking,5886.93
41,ORD2041,2025-02-28,CUST1041,Delhi,Smartwatch,Accessories,3,7462,0,22386.00,Net Banking,4477.20
1,ORD2001,2025-02-11,CUST1001,Hyderabad,Tablet,Accessories,3,8681,15,22136.55,Cash,4427.31
5,ORD2005,2025-01-11,CUST1005,Bangalore,Tablet,Electronics,1,17200,10,15480.00,Cash,3096.00
24,ORD2024,2025-01-01,CUST1024,Hyderabad,Laptop,Electronics,1,12564,10,11307.60,Debit Card,2261.52
34,ORD2034,2025-02-01,CUST1034,Bangalore,Laptop,Electronics,1,10987,5,10437.65,Cash,2087.53
13,ORD2013,2025-01-11,CUST1013,Bangalore,Headphones,Electronics,4,2663,15,9054.20,UPI,1810.84
18,ORD2018,2025-01-20,CUST1018,Mumbai,Smartwatch,Electronics,5,2003,15,8512.75,UPI,1702.55
42,ORD2042,2025-01-01,CUST1042,Bangalore,Smartwatch,Accessories,4,1587,5,6030.60,Net Banking,1206.12